version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database-facturier
    ports:
      - 3306:3306

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/database-facturier?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
