
### Total mensuelles du montant des factures pour un utilisateur (OK)
GET http://localhost:8082/fee/sumFeeForCurrentMonthByPerson/0723546741

### Nombre de factures en attentes pour un utilisateur (OK)
GET http://localhost:8082/user/fees/invoicesOutstanding?phone=0723546744

### Total mensuel du mantant des factures payées pour un utilisateur (OK)
GET http://localhost:8082/user/fees/month?phone=0723546744

### Total annuel du mantant des factures payées pour un utilisateur (OK)
GET http://localhost:8082/user/fees/year?phone=0723546744

### ajout de date de debut et une date de fin (A FAIRE) (en fonction de la period de la facture)
GET http://localhost:8082/fee/findFeeByBillNumberFalseBetweenDate?phone=0723546741&startDate=2023-03-01&endDate=2023-07-01

### Trouver une facture graçe au numero de la facture
GET http://localhost:8082/user/billNumberFalse?numberBill=01034576899876244320

### Total du mantant des toutes les factures payées pour un utilisateur (OK)
GET http://localhost:8082/fee/countFeeByPerson/0723546741

### Liste de factures à payées pour un utilisateur (OK)
GET http://localhost:8082/user/fees?phone=0723546744&page=0&size=1

### Liste de factures payées pour un utilisateur (OK)
GET http://localhost:8082/user/fees/true?phone=0723546741&page=0&size=1

### Total du mantant des factures en attentes pour un utilisateur (OK)
GET http://localhost:8082/user/fees/outstanding?phone=0723546744

### Nombre de factures payées pour un utilisateur (OK)
GET http://localhost:8082/user/fees/number?phone=0723546741

### Liste des utilisateurs avec le rôle support
GET http://localhost:8082/user/getAllUserSupport?page=0&size=10

### Payer pour une tiers par un utilisateur (OK)
POST http://localhost:8082/fee/update/01034576899876244541
Content-Type: application/json

{
    "phone":"0723546741"
}

### Liste de factures payées pour une tiers par un utilisateur (OK)
GET http://localhost:8082/fee/findFeeByDebtor?debtor=0723546741&page=0&size=10

### Générere un lien de paiment par un utilisateur (tu dois gerez ça côté front)
GET http://localhost:8082/user/fees?phone=0723546744

### Liste des question pour la foire Aux Questions (FAQ)
### (Pas disponible)

### Soumettez une préoccupation par un utilisateur
### (Pas disponible aussi on doit le faire par mail)
POST http://localhost:8082/user/sendReclamation?email=melessangekevin@gmail.com
Content-Type: application/json

{
  "lastname":"meless",
  "firstname":"meless",
  "object":"Reclamation",
  "idProblem":"Impossibilité de voir le reçu",
  "idOperator":"CIE",
  "message":"uhrfghkjdskfhgukdfkjgfhdkhukhgkuhuh"

}


### Envoyer un message a un agent support (OK)
POST http://localhost:8082/user/sendMessage
Content-Type: application/json

{
    "senderEmail": "fact1@gmail.com",
    "receiptEmail": "fact5@gmail.com",
    "message":"blabla"
}

### Liste des messages échangés entre un agent support et un utilisateur (AJOUTER UNE PAGINATION)
GET http://localhost:8082/user/messages?sender=fact5@gmail.com&receipt=fact1@gmail.com

### Changer la photo de profil d'un utilisatuur
### (Pas disponible)

### Changer les informations d'un utilisatuur (Renvoyez du JSON)
POST http://localhost:8082/user/update/1
Content-Type: application/json

{
  "firstname": "meless",
  "lastname": "meless",
  "email": "meless@maile.com",
  "phone": "0707359590",
  "index": "224"
}

### Inscription d'un nouvel utilisatuur (OK)
POST http://localhost:8082/user/add
Content-Type: application/json

{
  "firstname": "meless",
  "lastname": "meless",
  "email": "meless@mail.com",
  "phone": "0707359590",
  "country": 1,
  "city": 1,
  "street": "azito",
  "password":"1234567890"
}

### Liste des facturiers (disponible à prochaine mise à jour)
GET http://localhost:8082/user/listOfUsersOperator

### Obtenir la liste des factures par numéro d'identifiant du client(010345768998761) (OK)
GET http://localhost:8082/fee/findAllFeeByUser?feeId=010345768998761

### Obtenir une facture par son identifiant (prochaine mis à jour) -----------------------------
GET http://localhost:8082/fee/downloadInvoices?numberBill=01034576899876244541

### modifier mot de passe (prochaine mis à jour)
POST http://localhost:8082/user/updatePassword/1
Content-Type: application/json

{
    "password":"1234567890"
}

### téléchargement de reçu (prochaine mis à jour)
GET http://localhost:8082/fee/downloadInvoices?numberBill=01034576899876244541

### Rechercher une facture par date ou par l'identifiant de la facture
GET http://localhost:8082/fee/searchByFeeIdOrPaymentDate?date=2023-04-18

### Recherche par facturier, status de la facture, date de debut et de fin (prochaine mis à jour)
GET http://localhost:8082/fee/searchFeeByDateStatus?startDate=2023-06-03 &endDate=2023-07-03&status=0&label=CIE

### --- ESPACE FACTURIER ---

### total des montants de factures mensuel pour un facturier
GET http://localhost:8082/fee/getAllFeeByOperator?role=CIE

### nombre des factures mensuelles payées (mois en cours)
GET http://localhost:8082/fee/getNumberOfInvoicesForCurrentMonth?role=CIE

### nombre des factures mensuelles payées (au choix le mois et l'année sont obligatoire)
GET http://localhost:8082/fee/getNumberOfInvoicesForMonthAndYear?month=4&year=2023&role=CIE

### nombre des factures en attentes de payement
GET http://localhost:8082/fee/numberOfAvailableBills?role=SODECI
### http://localhost:8082/fee/getAllFeeStatusFalseByOperator?role=SODECI&page=0&size=10

### liste des factures payées pour le facturier connecté
GET http://localhost:8082/fee/getAllFeeStatusTrueByOperator?role=SODECI&page=0&size=10

### liste des factures chargées
GET http://localhost:8082/fee/findAllBillsPerOperator?role=CIE&page=0&size=10

### chargement de factures par le facturier (fichier excel)
### tu utilises formaData aussi file est la seule donnée à inserer
POST http://localhost:8082/fee/uploadInvoices?file=factures.xlsx

### Facture en attente (nombre)
GET http://localhost:8082/fee/numberOfPendingBillsPerOperator?role=SODECI

### Factures payées (nombre)
GET http://localhost:8082/fee/numberOfPaidBillsPerOperator?role=SODECI

### Montant des factures (mensuel)
GET http://localhost:8082/fee/billsAmountPerMonth?role=SODECI

### Factures ajoutées (liste)
GET http://localhost:8082/fee/findAllBillsPerOperator?role=SODECI

### Liste des operations (Liste des factures payées)
GET http://localhost:8082/fee/getAllFeeStatusTrueByOperator?role=SODECI&page=0&size=10

### Importer les factures via fichiers excel
POST http://localhost:8082/fee/uploadInvoices?file=factures.xlsx

### Factures ajoutée (nombre)
GET http://localhost:8082/fee/numberOfBillsAddingPerOperator?role=SODECI

### Factures en attente (nombre)
GET http://localhost:8082/fee/numberOfPendingBillsPerOperator?role=SODECI

### Factures payées (nombre)
GET http://localhost:8082/fee/numberOfPaidBillsPerOperator?role=SODECI

### Factures impayées (nombre)
GET http://localhost:8082/fee/numberOfPendingBillsPerOperator?role=SODECI

### Ventes réalisées (total) un an
GET http://localhost:8082/fee/numberOfPaidBillsPerOperatorPerYear?role=SODECI

### Chiffres d'affaires (total) un an
GET http://localhost:8082/fee/numberOfPaidBillsPerOperatorPerYear?role=SODECI

### Bénéfice réalisées (total) un an
GET http://localhost:8082/fee/numberOfPaidBillsPerOperatorPerYear?role=SODECI


### Statistique
GET http://localhost:8082/fee/sumInvoicesPaidPerMonthOfTheCurrentYearPerOperator?role=SODECI


### --- ESPACE ADMIN ---

### requête de creation d'un compte facturier ou support
POST http://localhost:8082/user/add-support-or-biller?roleId=3
Content-Type: application/json

{
    "firstname": "meless",
    "lastname": "meless",
    "email": "meless@mail.com",
    "phone": "0707359590",
    "country": 1,
    "city": 1,
    "street": "azito",
    "password":"1234567890"
}

###--------------------------------

### liste operateur
GET http://localhost:8082/operator/all

### Nombre de facturier ( nombre total de facture)
GET http://localhost:8082/operator/numberOfOperator

### Nombre de client (nombre total utilisateurs payeur )
GET http://localhost:8082/user/numberOfPayingUsers

### Factures payées ( nombre facture payée )
GET http://localhost:8082/fee/numberBillsPaid

### Montant factures ( somme des factures payées )
GET http://localhost:8082/fee/sumBillsPaid

### Facture Disponible ( factures disponible ) PAUL
GET http://localhost:8082/fee/findUnpaidBills?page=0&size=10

### Facture impayées  ( factures impayées ) PAUL
GET http://localhost:8082/fee/findUnpaidBills?page=0&size=10

### Nombre de factures générée
GET http://localhost:8082/fee/numberGeneratedBills

### Nombre de factures non payée
GET http://localhost:8082/fee/numberOfUnpaidBills

### Chiffres d'affaires sur un an
GET http://localhost:8082/fee/sumBillsPaidPerYear

### Historique (Factures )
GET http://localhost:8082/fee/findGeneratedBills?page=0&size=10

### Les Facturiers (La liste des facturiers)
GET http://localhost:8082/operator/all

### Nombres d'annonces réalisées Mensuel
GET http://localhost:8082/announcement/numberAnnouncementPerMonth

### Nombres d'annonces réalisées Annuel
GET http://localhost:8082/announcement/numberAnnouncementPerYear

### Listing Annonceurs
GET http://localhost:8082/announcement/findAll

### Formulaire Annonce (ajout d'une annonce)
### J'ai pas trouver d'exemple d'ajout avec JSON. tu feras ça avec du formDATA (React) voir fichier exempleFormData.txt
POST http://localhost:8082/announcement/add-new

### Client actifs (nombre)
GET http://localhost:8082/user/numberOfActivatedUser

### Client inactifs (nombre)
GET http://localhost:8082/user/numberOfInactivatedUser

### Client total (nombre)
GET http://localhost:8082/user/numberOfUser

### Liste des clients
GET http://localhost:8082/user/listOfCustomer

### Formulaire ajout facturier
POST http://localhost:8082/user/add-support-or-biller?roleId=2
Content-Type: application/json

{
  "firstname": "meless",
  "lastname": "meless",
  "email": "meless@mail.com",
  "phone": "0707359590",
  "country": 1,
  "city": 1,
  "street": "azito",
  "password":"1234567890"
}

### Chiffres d'affaires Facturier
GET http://localhost:8082/fee/sumBillsPaid

### Chiffres d'affaires Mensuelle
GET http://localhost:8082/fee/sumBillsPaidPerMonth

### Chiffres d'affaires Total
GET http://localhost:8082/fee/sumBillsPaid

### Performance evolutive
http://localhost:8082/fee/sumInvoicesPaidPerMonthOfTheCurrentYear

### total Message en attente

### Total message annuel
GET http://localhost:8082/message/totalMessagePerYear

### Total message mensuel
GET http://localhost:8082/message/totalMessagePerMonth

### Liste des utilisateurs avec qui l'admin à conversé
GET http://localhost:8082/message/findUserDiscussAdmin?mail=factSupport0LN@gmail.com

### Liste des messages entre l'admin et un utilisateur
GET http://localhost:8082/user/messages?sender=admin@mail.com&receipt=user@mail.com

### Compte total (nombre)
GET http://localhost:8082/user/numberOfUser

### Compte Actif (nombre)
GET http://localhost:8082/user/numberOfActivatedUser

### Compte inactif (nombre)
GET http://localhost:8082/user/numberOfInactivatedUser

### Formulaire de creation des rôles
POST http://localhost:8082/role/addRole
Content-Type: application/json

{
  "name":"User-1"
}








