
### Total mensuelles du mantant des factures pour un utilisateur
GET http://localhost:8082/fee/sumFeeForCurrentMonthByPerson/0723546741

### Nombre de factures en attentes pour un utilisateur
GET http://localhost:8082/user/fees/invoicesOutstanding?phone=0723546744

### Total mensuel du mantant des factures payées pour un utilisateur
GET http://localhost:8082/user/fees/month?phone=0723546744

### Total annuel du mantant des factures payées pour un utilisateur
GET http://localhost:8082/user/fees/year?phone=0723546744

### Total du mantant des toutes les factures payées pour un utilisateur
GET http://localhost:8082/fee/countFeeByPerson/phone=0723546744

### Liste de factures a payées pour un utilisateur
GET http://localhost:8082/user/fees?phone=0723546744

### Liste de factures payées pour un utilisateur
GET http://localhost:8082/user/fees/true?phone=0723546744

### Total du mantant des factures en attentes pour un utilisateur
GET http://localhost:8082/user/fees/outstanding?phone=0723546744

### Nombre de factures payées pour un utilisateur
GET http://localhost:8082/user/fees/number?phone=0723546744

### Liste des contacts pour un utilisateur
GET http://localhost:8082/user/getAllUserSupport

### Payer pour une tiers par un utilisateur
POST http://localhost:8082/fee/update/1/fact1@gmail.com
Content-Type: application/json

{
  "debtor": "fact1@gmail.com"
}

### Liste de factures payées pour une tiers par un utilisateur
GET http://localhost:8082/fee/getFee/mail@mail.com

### Générere un lien de paiment par un utilisateur (tu dois gerez ça côté front)
GET http://localhost:8082/user/fees?phone=0723546744

### Liste des question pour la foire Aux Questions (FAQ)
### (Pas disponible)

### Soumettez une préoccupation par un utilisateur
### (Pas disponible aussi on doit le faire par mail)

### Liste des agents supports
GET http://localhost:8082/user/getAllUserSupport

### Envoyer un message a un agent support
POST http://localhost:8082/user/sendMessage
Content-Type: application/json

{
    "senderEmail": "fact1@gmail.com",
    "receiptEmail": "fact5@gmail.com",
    "message":"blabla"
}

### Liste des messages échangés entre un agent support et un utilisateur
GET http://localhost:8082/user/messages?sender=fact5@gmail.com&receipt=fact2@gmail.com

### Changer la photo de profil d'un itilisatuur
### (Pas disponible)

### Changer les informations d'un utilisatuur
POST http://localhost:8082/user/update/1
Content-Type: application/x-www-form-urlencoded

firstname=meless&lastname=meless&email=meless@mail.com&phone=0707359590&index=224

### Inscription d'un nouvel utilisatuur
POST http://localhost:8082/user/add
Content-Type: application/json

{
  "firstname": "meless",
  "lastname": "meless",
  "email": "meless@mail.com",
  "phone": "0707359590",
  "country": 1,
  "city": 1,
  "street": "azito",
  "password":"1234567890"
}